language: java
sudo: false
addons:
  chrome: stable
  apt:
    packages:
    - httpie
    - jq
env:
  global:
  - WEB_SERVER=http://localhost:5516
  - BROWSER=chrome
  - secure: XPCc0BKkBkxZ0yxadNfHgnO8/z/uiRXDLWVFM2zUgHFdsIO0dGCR9yCZ29oQEZq5mQNTBXHMlWUtyWWIuh0dI6Unqf9t6NXwM3Rrdt+5nrspVuVU8rlbZk5VL4qwlDyCMy0C7Jt6UkGQm07BB2wm1iWwosU85haK66qBKKXCJoA=
  - secure: Y2vWbrGiUn98si2mooO02v00ksleu4GYSZhZHmgznNXvzH1ruPpC+fzE23foSkb2vvM1os86tmxeOy+MCJsPoOLF1hI8cJKm8UjBJZX595Pli8YwJcmtdCLsmT+W1u+iDm7mUlMJtFRr9EkDZ1Kuou7a76N/R8xaBTKJc/n8sUs=
  - secure: hiYpM0Zbcy0yGc7Ip/AKNhKU5e441V0AEiLoWnPkKLyjG7phUTGBsh9ZM+0vR1UEOzsbqAw5V7Lr/Q639+sz+u2IsEB3Akwre8RXDxzYMAeUPriNi+5D/zT8yR5Y8QQB1vEQ1wQPQW23tPNUQVwytZGeoifjpNZ+f4cyrw1Zn3A=
  - secure: GqSqGY6Rlz6HhVGRrOL+R0QV4KT43Q2//c1ahnPrkWfAP8bc4Px6z+nKK46Er8J6sIAU1c8eQLQSXHZTOdEPRBC+gw9u8ONpBeSseq0z+CDxgV442r1y+Earp1353GFFDIltqXtrn3N1FOlN76kORxhCtdo+1vJFlbHmvWxCW/Y=
  - secure: JQIAlH4UJJe29LHEpQ5RhAW2Se8TZj9UnGgDNHILtVlhjEPOyQoIpVot+7Ej29ZE1freCXT6azSx4y7QYZAEVAibswVGsWpfE/Mx71fNfnrQ7poxNPEmwjbpGXBSR96FSvm/I8jODxDIuaY5HB3B+gtk53Fyb4hDkz8EGM/MV9k=
script:
- mkdir -p ./xl-licenses
- http --check-status --print=b --auth $username:$password --json POST https://download.xebialabs.com/api/temporary/xl-release
  firstName=xlc lastName=xlc email=xlc@xebialabs.com company=xebialabs | jq --raw-output
  '.license' > ./xl-licenses/xl-release-license.lic
- "./gradlew clean assemble"
- docker run --rm -d -v $PWD/build/libs/.:/opt/xlr/server/plugins/__local__ -v $PWD/xl-licenses:/license
  -p 5516:5516 --name xlr xebialabs/xl-docker-demo-xlr:latest
- sleep 60
- docker logs xlr
- "./gradlew itest"
- docker stop xlr
notifications:
  slack:
    secure: WzdS5sSSQziwbZwqW8nCddRGC8SSrgcPyVn9NbV2MOkqa4mFawQOL05CCOc0RfV7otCCqxsDqXAehuyKzEVA8VrQ1g10Eelppbnv9WxDYzIj1M2MPmyo4RzHK6+aw0KRIujufgYQdxit+N/J2xATnUy+3hiXBQprCnIGXYaNk2w=
  hipchat:
    rooms:
      secure: A0rtcc5iWVOiKodiYxX8DzNn777k2boUWILXtfEKKXqHzxENYaj5EHeMT+kC+2F/rnnjS79fMFD9VU4d/dbjiQH4wzHMPA5gBGpOpb+q0zbLTxt4sYmn+9HqVoIu774ZSBkX1fh5y/MM6qrjUJbPLMuBylM88PhYu95hGL7TW1w=
deploy:
  provider: releases
  api_key:
    secure: MDy/R3WGvW3rGg9YEEBzGkZtKMK8EEwR/+xoX2ynXrEKGGiXEmCLeJ1i+X5v1N+Wn7y86t9zkwBtMRgWDbHOQMPRv+XcBpJXIKbS+KSkzKbDVEBk9m8Qh8XxhSDUWhjIBiVfUe4/jrEVHE9vIXGFoikLMf9IQyLgeOEkLDLs6ag=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_bracnhes: true
    tags: true
    repo: xebialabs-community/xlr-servicenow-plugin
